language: node_js
node_js:
  - 0.10
  - 0.11
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-p' ]; then cd .. && eval "mv $currentfolder generator-p" && cd generator-p; fi
